Auth second
Failless/FaillessDB pull request #3
Opened 2019-11-25 22:16 UTC by Serjio2888

2019-11-26 12:01 UTC, egogoger reviewed
Поправь пулл реквест
data_worker, node, failless_cli, failless_db

Исправь пути в define  и хедера в соответствии с Google Style Guide

А в целом пушка

2019-11-26 12:01 UTC, egogoger commented on tests/tests_db/test_auth.h
>      std::string login;
В этом файле исправь путь в  define

2019-11-26 12:01 UTC, egogoger commented on llssdb/auth/authorization.h
>      bool IsAuth(std::string login, std::string pass, int table_id) override;
Если функция не должна изменять переданные ей аргументы - то передавай их через константную ссылку

2019-11-26 12:01 UTC, egogoger commented on llssdb/common/settings.h
> +            };
Пропиши список инициализации по-гугловски
https://google.github.io/styleguide/cppguide.html#Constructor_Initializer_Lists

2019-11-26 12:01 UTC, egogoger commented on llssdb/auth/authorization.cpp
> +        salt[j++] = login[i];  // salt - reversed login - unique
Итератор j тебе дальше по функции не нужен, поэтому инициализируй его внутри for()

2019-11-26 12:01 UTC, egogoger commented on llssdb/auth/authorization.cpp
> +    A.Registration("fuck", "dick");
Давай без шуток на проде

2019-11-26 12:01 UTC, egogoger commented on llssdb/auth/authorization.h
> +#include <boost/algorithm/hex.hpp>
Хедера в порядок приведи (Google style)

2019-11-26 12:01 UTC, egogoger commented on llssdb/utils/config_manager.cpp
> +    }
Лучше заранее проверить наличие файла через access("file_path", R_OK)

2019-11-26 12:01 UTC, egogoger commented on llssdb/auth/authorization.cpp
> +        return false;
Выводи описание ошибки, что б дебажить было проще

2019-11-26 12:01 UTC, egogoger commented on llssdb/auth/authorization.h
> +    bool IsAuth(std::string login, std::string pass, int table_id) override;
Коммент где-то потерялся, поэтому повторю

Если не изменяешь аргументы в функции и они потенциально могут много весить или имеют сложную инициализацию - то передавай их через константную ссылку

2019-11-26 12:01 UTC, egogoger commented on llssdb/auth/user_info.h
> +#include <boost/uuid/uuid_generators.hpp>
Путь в define и хедера по алфавиту

2019-11-26 12:01 UTC, egogoger commented on llssdb/auth/iauthorization.h
> +#include <map>
Путь в define и хедера по алфавиту

2019-11-26 12:01 UTC, egogoger commented on llssdb/auth/user_info.h
> +    UserInfo() : client_id(boost::uuids::random_generator()()), is_conn(false), table_id(-1) {}
pass_hash(nullptr) забыл
Да и разве не нужно ли этой структуре больше конструкторов?

2019-11-26 12:01 UTC, egogoger commented on llssdb/engine/server_manager.h
> +#include "folder/node.h"
Ноды больше нет

2019-11-26 12:01 UTC, egogoger commented on llssdb/folder/data_worker.cpp
> +#include "data_worker.h"
Дата воркера тоже больше нет

2019-11-26 12:01 UTC, egogoger commented on llssdb/utils/config_manager.h
> +#include <algorithm>
Хедера
Дальше сам поищешь какие надо поправить

2019-11-26 12:01 UTC, egogoger commented on tests/tests_db/run_tests.cpp
> +#include "tests/tests_db/test_config.h"
tests/tests_db/test_file_system.h не хватает

2019-11-26 12:01 UTC, egogoger commented on llssdb/auth/authorization.cpp
> +    UserInfo *User = new UserInfo;
Раз уж использовал auto так используй везде

2019-11-26 12:01 UTC, egogoger commented on llssdb/auth/authorization.cpp
> +    Users_[login] = *User;
map Users_  у тебя хранит статические переменные.
Зачем тогда динамически выделять память на UserInfo? Сам знаешь, new/malloc - операция затратная

Пропиши конструктор как раз для этого случая и будет тебе красивая и экономичная инициализация Users_[login] = UserInfo(*args, **kwargs) 
:)

2019-11-26 12:01 UTC, egogoger commented on llssdb/auth/authorization.cpp
> +    if (Users_[login].pass_hash == pass_hash) {
Тут тоже, в принципе, можешь не хранить переменную, которая тебя нужна в одном единственном месте

2019-11-26 12:38 UTC, rowbotman requested changes
Проверить перед мержем, что:

- Возвращается валидные указатели
- Наборы байт сравниваются корректно

2019-11-26 12:38 UTC, rowbotman commented on llsscli/core/client.cpp
> +#include "client.h"
В хедерах пишем полные пути

2019-11-26 12:38 UTC, rowbotman commented on llsscli/core/client.h
> +#include "network/mp_client.h"
Полные пути

2019-11-26 12:38 UTC, rowbotman commented on llsscli/filesystem/filesystem.cpp
> +#include "filesystem.h"
Полные пути

2019-11-26 12:38 UTC, rowbotman commented on llsscli/network/mp_client.cpp
> +#include "mp_client.h"
полные

2019-11-26 12:38 UTC, rowbotman commented on llssdb/auth/authorization.cpp
> +bool simpleSHA256(void *input, unsigned long length, unsigned char *md) {
Названия функций с большой буквы

2019-11-26 12:38 UTC, rowbotman commented on llssdb/auth/authorization.cpp
> +        return false;
Если будут юнит-тесты, то не надо - в тестах все равно увидишь, что не пашет

2019-11-26 12:38 UTC, rowbotman commented on llssdb/auth/authorization.cpp
> +    return SHA256_Final(md, &context) != 0;
можно без `!= 0`
Если функция вернет ноль, то `!= ` преобразуется в 0

2019-11-26 12:38 UTC, rowbotman commented on llssdb/auth/authorization.cpp
> +    std::string salt = login;
Про это уже писал
Бесполезное копирование,  потому что ты login не меняешь

2019-11-26 12:38 UTC, rowbotman commented on llssdb/auth/authorization.cpp
> +    for (int i = login.size() - 1; i >= 0; --i)
Скобки после 
```cpp
for (...) {
...
}
```

2019-11-26 12:38 UTC, rowbotman commented on llssdb/auth/authorization.cpp
> +        std::cerr << "error in hasher" << std::endl;
Нет обработки ошибок, хоть `nullptr` верни

2019-11-26 12:38 UTC, rowbotman commented on llssdb/auth/authorization.cpp
> +    return md;
Возвращаешь невалидный указатель. Ссылается на память, которая по завершению функции вернется ядру
critical!!!
#3

2019-11-26 12:38 UTC, rowbotman commented on llssdb/auth/authorization.cpp
> +    return u_id == table_id && u_hash == pass_hash;
Бесполезное ревью, потому что ты походу ничего из того, что я написал в предыдущем, не исправил
по прежнему проверяешь указатели, а не набор байт на равенство

2019-11-27 07:39 UTC, rowbotman reviewed
Исправь плз все, что написал

2019-11-27 07:39 UTC, rowbotman commented on llssdb/auth/authorization.cpp
> +    auto *md = new unsigned char[SHA256_DIGEST_LENGTH]; // 32 bytes
мы вроде сошлись, что ты не будешь выделять память, а будешь передавать в функцию указатель на массив чаров, а потом инициализировать его хэшом

2019-11-27 07:39 UTC, rowbotman commented on llssdb/auth/authorization.cpp
> +    if (Users_[login].pass_hash == pass_hash) {
Сравниваешь указатели
Сравнивай наборы байт

2019-11-27 07:39 UTC, rowbotman commented on llssdb/auth/authorization.cpp
> +    unsigned char *u_hash = Users_[login].pass_hash;
зачем указатель, если можно использовать `Users_[login].pass_hash`

2019-11-27 07:39 UTC, rowbotman commented on llssdb/auth/authorization.cpp
> +    UserInfo User;
Конструктор где?

2019-11-27 07:39 UTC, rowbotman commented on llssdb/auth/user_info.h
> +//
убери

2019-11-27 07:39 UTC, rowbotman commented on llssdb/auth/authorization.h
> +
убери

2019-11-27 07:39 UTC, rowbotman commented on llssdb/auth/authorization.cpp
> +        std::cerr << "error in hasher" << std::endl;
не исправил

2019-11-27 07:39 UTC, rowbotman commented on llssdb/auth/user_info.h
> +
Конструкторы другие где?

2019-11-27 07:39 UTC, rowbotman commented on llssdb/auth/user_info.h
> +    unsigned char *pass_hash;
сделай массивом, потому что постоянно одна и тот же размер

2019-11-27 07:39 UTC, rowbotman commented on llssdb/common/settings.h
> +        }  // namespace common
отступы приведи в порядок

2019-11-27 07:39 UTC, rowbotman commented on llssdb/common/task.cpp
> +    return !(time != r.time);
too complicated
`time == r.time`

2019-11-27 07:39 UTC, rowbotman commented on llssdb/engine/server_manager.h
> +#include "folder/node.h"
не исправил

2019-11-27 07:39 UTC, rowbotman commented on llssdb/engine/server_manager.cpp
> +#include "server_manager.h"
полные пути

2019-11-27 07:39 UTC, rowbotman commented on llssdb/engine/server_manager.h
> +#include "folder/task.h"
полные пути

2019-11-27 07:39 UTC, rowbotman commented on llssdb/engine/task.cpp
> +#include "task.h"
полные пути

2019-11-27 07:39 UTC, rowbotman commented on llssdb/folder/data_worker.cpp
> +#include "data_worker.h"
не исправил

2019-11-27 07:39 UTC, rowbotman commented on llssdb/folder/node.cpp
> +#include "node.h"
файла больше нет

2019-11-27 07:39 UTC, rowbotman commented on llssdb/folder/task_worker.cpp
> +#include "folder/task_worker.h"
полные пути

2019-11-27 07:39 UTC, rowbotman commented on llssdb/network/tcp_server.cpp
> +#include "tcp_server.h"
полные

2019-11-27 07:39 UTC, rowbotman commented on llssdb/network/tcp_server.h
> +#include "tcp_server_interface.h"
полные

2019-11-27 07:39 UTC, rowbotman commented on llssdb/network/tcp_server_interface.h
> +#include "network/transfer/response.h"
полные

2019-11-27 07:39 UTC, rowbotman commented on llssdb/network/transfer/request.cpp
> +#include "request.h"
полные

2019-11-27 07:39 UTC, rowbotman commented on llssdb/network/transfer/response.h
> +#include "request.h"
полные

2019-11-27 07:39 UTC, rowbotman commented on llssdb/utils/config_manager.cpp
> +    const char *config_path = "../../failless.conf";
вынеси это в конструктор, потому что так хардкодить путь до конфига - это такое себе
конфиг будет задаваться из мейна

2019-11-27 07:39 UTC, rowbotman commented on llssdb/network/transfer/response.h
> +#include "request.h"
полные

2019-11-27 07:39 UTC, rowbotman commented on llssdb/utils/config_manager.h
> +#include <llssdb/common/settings.h>
убери инклуды, которые не используешь в **ЭТОМ** файле
Те, которые используешь в `.cpp` помести в `.cpp`

2019-11-27 07:39 UTC, rowbotman commented on llssdb/utils/config_manager.h
> +#include <llssdb/common/settings.h>
И у своих хедеров у нас такие  `""` кавычки

2019-11-27 07:39 UTC, rowbotman commented on llssdb/utils/config_manager.cpp
> +    if (access(config_path, R_OK) == -1) {
сишная фукция
перепеши на с++, с учетом того, что есть такая вещь, как `boost::filesystem`

2019-11-27 07:39 UTC, rowbotman commented on llssdb/utils/config_manager.cpp
> +failless::db::utils::ConfigManager::WriteToSettings_(failless::db::common::Settings &settings, std::ifstream &cFile) {
google code style отдел namespases почитай

2019-11-27 07:39 UTC, rowbotman commented on llssdb/utils/config_manager.cpp
> +    while (getline(cFile, line)) {
если ты объявляешь переменную, то всегда ее инициализируй (кроме случаев, когда это невозможно)

2019-11-27 07:39 UTC, rowbotman commented on llssdb/utils/config_manager.cpp
> +    while (getline(cFile, line)) {
разве `getline` не в пространстве `std`?

2019-11-27 07:39 UTC, rowbotman commented on llssdb/utils/config_manager.cpp
> +        auto value = line.substr(delimiterPos + 1);
почему `auto`? Этож `size_t` и `std::string`
`auto` только для типов, которые долго писать. обычно используется

2019-11-27 07:39 UTC, rowbotman commented on llssdb/utils/config_manager.cpp
> +            if (std::stoi(value) == 1) {
зачем число? просто в конфиге напиши true и сравнивай на true без лишних приводов к числу

2019-11-27 07:39 UTC, rowbotman commented on llssdb/utils/config_manager.cpp
> +            if (std::stoi(value) == 1) {
тем более, что это символ, так что можно просто сравнить line == "1"

2019-11-27 07:39 UTC, rowbotman commented on llssdb/utils/config_manager.cpp
> +            }
аналогично тому, что выше

2019-11-27 07:39 UTC, rowbotman commented on tests/tests_db/test_config.h
> +
убери

2019-11-28 14:47 UTC, rowbotman reviewed
Лучше, но есть еще, что исправить

2019-11-28 14:47 UTC, rowbotman commented on llssdb/auth/authorization.cpp
> +        salt[j++] = login[i];  // salt - reversed login - unique
это не должно работать, потому что в salt нет символов, а ты к ним обращаешься

2019-11-28 14:47 UTC, rowbotman commented on llssdb/auth/authorization.cpp
> +    if (!SimpleSHA256(reinterpret_cast<unsigned char *>(&pass), pass.size(), md)) {
pass - строка, а ты получаешь ее указатель, чтобы потом привести его к char
надо `pass.c_str()`, которая вернет `const char*`

2019-11-28 14:47 UTC, rowbotman commented on llssdb/auth/authorization.cpp
> +Authorization::Hasher_(const std::string &login, std::string pass, unsigned char *md) {
по гугловскому стилю то, что в функции или методе изменяется (в данном случае это md), должно идти первым в списке параметров функции

2019-11-28 14:47 UTC, rowbotman commented on llssdb/auth/authorization.cpp
> +    if (Users_[login].pass_hash == pass_hash) {
массивы на равенство проверяются не так

2019-11-28 14:47 UTC, rowbotman commented on llssdb/auth/authorization.cpp
> +        Users_.erase(login);
зачем удаляешь login?

2019-11-28 14:47 UTC, rowbotman commented on llssdb/auth/authorization.cpp
> +    }
```cpp
return Users_.count(login) ? true : false;
```

2019-11-28 14:47 UTC, rowbotman commented on llssdb/common/settings.h
> +}  // namespace failless
исправь отступы

2019-11-28 14:47 UTC, rowbotman commented on llssdb/utils/config_manager.cpp
> +bool failless::db::utils::ConfigManager::Initialize(failless::db::common::Settings &settings) {
пиши в
```cpp
namespace foo {
namespace bar {
}
}
```

2019-11-28 14:47 UTC, rowbotman commented on llssdb/utils/config_manager.h
> +}  // namespace failless
отступы исправь

2019-11-28 14:47 UTC, rowbotman commented on llssdb/utils/config_manager.h
> +                const char *config_path;
указатель не должен быть конст
либо вынести в константу
да и для пути лучше `std::string`

2019-12-08 10:43 UTC, closed without merging